name: Test the project and build docker container on aws

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-go@v2
        - uses: actions/checkout@v2
          with:
            go-version: ^1.13
          id: go
        - run: go test -v .
    
        - name: AWS SSM Send-Command
          uses: peterkimzz/aws-ssm-send-command@1.0.2
          id: ssm
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2
            instance-ids: ${{ secrets.INSTANCE_ID }}
            working-directory: /home/ec2-user/ahoi-kino
            command: git pull && docker-compose up -d
            comment: Pull and docker-compose
